#
# (C) Copyright 2018 Dream Chip Technologies GmbH 
# Thomas Metzler <thomas.metzler@dreamchip.de>
#
# (C) Copyright 2001-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= arria10som_base.o arria10som_common.o
